### ISSUE TITLE
DoubleColumn not  implementing CategoricalColumn

### ISSUE THREAD

**Issue by wokere** [jtablesaw/tablesaw#1156]
Hi, I am having trouble summarizing an specific column when the other one is DoubleColumn, as not implements CategoricalColumn throws an error when by()  is inovked.

**Comment by lwhite1** [comment]
Sorry you’re having trouble.  You need to provide code that shows what
you’re doing for someone to help you.

**Comment by wokere** [comment]
To reproduce:
csv file:

State,Scale,Injuries
ES,1.0,200
ES,-1.5,200
FR,-1.5,200
FR,2.0,1400

`

Table table = Table.read().file("src/main/resources/csv.csv");
 table.summarize("Injuries", sum).by("Scale", "State");
`

Throws:

Exception in thread "main" java.lang.ClassCastException: class tech.tablesaw.api.DoubleColumn cannot be cast to class tech.tablesaw.api.CategoricalColumn (tech.tablesaw.api.DoubleColumn and tech.tablesaw.api.CategoricalColumn are in unnamed module of loader 'app') at tech.tablesaw.table.Relation.categoricalColumn(Relation.java:467) at tech.tablesaw.api.Table.categoricalColumns(Table.java:416) at tech.tablesaw.table.StandardTableSliceGroup.create(StandardTableSliceGroup.java:59) at tech.tablesaw.aggregate.Summarizer.by(Summarizer.java:163) at org.example.Main.main(Main.java:13)

**Comment by lwhite1** [comment]
You can convert the DoubleColumn to a StringColumn using asStringColumn
(IIRC - the method name might be slightly different). Then sum on the
scale, state as you are doing. "asStringColumn" creates a new column that
you would have to add to the table.
