### ISSUE TITLE
Plot raise Pebble related exception 

### ISSUE THREAD

**Issue by shilkazx** [jtablesaw/tablesaw#1262]
Using kotlin with 'tech.tablesaw:tablesaw-core:0.43.1', 'tech.tablesaw:tablesaw-jsplot:0.43.1'. Plot a timeseries just same as official example:
```
    // result is a Table instance
    val fig = TimeSeriesPlot.create("diff", result, "date", "diff")
    Plot.show(fig) 
```
If I use default dependency of pebble, it will raise:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.mitchellbosecke.pebble.attributes.MemberCacheUtils.<init>(MemberCacheUtils.java:19)
	at com.mitchellbosecke.pebble.attributes.DefaultAttributeResolver.<init>(DefaultAttributeResolver.java:16)
	at com.mitchellbosecke.pebble.extension.core.AttributeResolverExtension.getAttributeResolver(AttributeResolverExtension.java:14)
	at com.mitchellbosecke.pebble.extension.ExtensionRegistry.addExtension(ExtensionRegistry.java:144)
	at com.mitchellbosecke.pebble.extension.ExtensionRegistry.addExtension(ExtensionRegistry.java:77)
	at com.mitchellbosecke.pebble.PebbleEngine$Builder.buildExtensionRegistry(PebbleEngine.java:596)
	at com.mitchellbosecke.pebble.PebbleEngine$Builder.build(PebbleEngine.java:535)
	at tech.tablesaw.plotly.components.TemplateUtils.getNewEngine(TemplateUtils.java:39)
	at tech.tablesaw.plotly.components.Component.<init>(Component.java:25)
	at tech.tablesaw.plotly.components.Font.<init>(Font.java:46)
	at tech.tablesaw.plotly.components.Font.<init>(Font.java:9)
	at tech.tablesaw.plotly.components.Font$FontBuilder.build(Font.java:102)
	at tech.tablesaw.plotly.components.Layout.<clinit>(Layout.java:28)
	at tech.tablesaw.plotly.api.TimeSeriesPlot.create(TimeSeriesPlot.java:38)
	at com.shilka.wind.MainKt.main(Main.kt:63)
	at com.shilka.wind.MainKt.main(Main.kt)
Caused by: java.lang.RuntimeException: Could not load unsafe method set
	at com.mitchellbosecke.pebble.attributes.UnsafeMethods.createUnsafeMethodsSet(UnsafeMethods.java:35)
	at com.mitchellbosecke.pebble.attributes.UnsafeMethods.<clinit>(UnsafeMethods.java:17)
	... 16 more
Caused by: java.lang.NoSuchMethodException: java.lang.ThreadGroup.allowThreadSuspension(boolean)
	at java.base/java.lang.Class.getMethod(Class.java:2395)
	at com.mitchellbosecke.pebble.attributes.UnsafeMethods.parseMethodSpec(UnsafeMethods.java:57)
	at com.mitchellbosecke.pebble.attributes.UnsafeMethods.createUnsafeMethodsSet(UnsafeMethods.java:31)
	... 17 more
```
If I explicitly add the latest pebble(v3.2.2) as dependency, it would raise something different:
```
Raise runtime exception:
Exception in thread "main" java.lang.NoClassDefFoundError: com/mitchellbosecke/pebble/error/PebbleException
	at tech.tablesaw.plotly.api.TimeSeriesPlot.create(TimeSeriesPlot.java:38)
......
Caused by: java.lang.ClassNotFoundException: com.mitchellbosecke.pebble.error.PebbleException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
......
```

**Comment by ccleva** [comment]
Hi @shilkazx, thanks for the detailed report.

The `ThreadGroup.allowThreadSuspension` method was removed in [Java 21](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/ThreadGroup.html).

`pebble v3.2.2` does not use that method anymore, but there is a [breaking change in the 3.2.x API](https://github.com/PebbleTemplates/pebble?tab=readme-ov-file#breaking-changes-in-version-32x) so you cannot substitute this version directly.

The maintenance release of tablesaw announced in [this discussion](https://github.com/jtablesaw/tablesaw/discussions/1261) uses `pebble v3.2.2` so this should fix the issue you are facing.

This is a release candidate for the moment, so please let us know if it works for you or report any problem you have with it.

Thanks

**Comment by ccleva** [comment]
Thanks for your feedback @shilkazx, this is great news.

I intend to slowly converge towards the [original vision for v1.0](https://github.com/jtablesaw/tablesaw/discussions/1075), so if the maintainers want to revive the original project it should not be that complicated.

In the meantime, if you want to test future maintenance releases from the forked project and report any issue, that will be much appreciated. And feel free to contribute any fix there.

Best

**Comment by shilkazx** [comment]
> Thanks for your feedback @shilkazx, this is great news.
> 
> I intend to slowly converge towards the [original vision for v1.0](https://github.com/jtablesaw/tablesaw/discussions/1075), so if the maintainers want to revive the original project it should not be that complicated.
> 
> In the meantime, if you want to test future maintenance releases from the forked project and report any issue, that will be much appreciated. And feel free to contribute any fix there.
> 
> Best

Actually, I would like to contribute at everything(not only test), but I'm a newbie of tablesaw and lack of some knowledge about the project(like pebble in this issue).

**Comment by ccleva** [comment]
You are welcome to contribute on all aspects @shilkazx  :smiley: 

For the moment the focus is on maintenance, feel free to comment on [the release planning](https://github.com/tlabs-data/tablesaw/discussions/20).
