### ISSUE TITLE
Error when reading a CSV 

### ISSUE THREAD

**Issue by kreecha** [jtablesaw/tablesaw#181]
Trying to load CSV file to Table using code below even pass String or File into the Table both failed. 

Table ops1 = Table.read().csv("C:\\\Users\\\User HP\\\Desktop\\\SepRIB_ActID_Name_Usr_TIme_IP_Short.csv");

But got the error (see below).  I use verion 0.10.0 run on Netbeans 8.1:        
-----------------------------------------------------------------------------

Compiling 1 source file to C:\Projects\Java\AnalyseData\build\classes
C:\Projects\Java\AnalyseData\src\analysedata\AnalyseData.java:30: error: cannot access IntIterable
        Table ops4 = Table.read().csv(file);
  class file for it.unimi.dsi.fastutil.ints.IntIterable not found
1 error
C:\Projects\Java\AnalyseData\nbproject\build-impl.xml:929: The following error occurred while executing this line:
C:\Projects\Java\AnalyseData\nbproject\build-impl.xml:269: Compile failed; see the compiler error output for details.
BUILD FAILED (total time: 1 second)
--------------------------FULL ERROR--------------------------------------
Exception in thread "main" java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/ints/IntIterable
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at analysedata.AnalyseData.main(AnalyseData.java:30)
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.ints.IntIterable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
C:\Users\User HP\AppData\Local\NetBeans\Cache\8.1\executor-snippets\run.xml:53: Java returned: 1
BUILD FAILED (total time: 0 seconds)

**Comment by kreecha** [comment]
Sorry i noticed there is a need for addtional libraries

**Comment by adriens** [comment]
Use maven to add the dependency, it should be much easier to deal with the code samples :+1:

**Comment by kreecha** [comment]
Thank you it now works as expected. I was not aware of that it requires mavan to be frank. Anyway now i have done 😊
