### ISSUE TITLE
failed 'DataFrameJoinerTest'

### ISSUE THREAD

**Issue by agebhar1** [jtablesaw/tablesaw#213]
Running `mvn clean verify` the `DataFrameJoinerTest` (introduced and tested by commit 2ab52b1) fails with:
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.007 sec <<< FAILURE!
innerJoin(tech.tablesaw.join.DataFrameJoinerTest)  Time elapsed: 0.004 sec  <<< ERROR!
java.lang.IllegalArgumentException: Only joining on date columns is supported so far
        at tech.tablesaw.join.DataFrameJoiner.inner(DataFrameJoiner.java:27)
        at tech.tablesaw.join.DataFrameJoinerTest.innerJoin(DataFrameJoinerTest.java:33)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

I do not understand why the [Travis CI build](https://travis-ci.org/jtablesaw/tablesaw/builds/313343011#L4362) passes.

![2ab52b1-tablesaw](https://user-images.githubusercontent.com/2443866/34072328-b698352a-e285-11e7-95c0-227ec88a40ad.png)

The type of `column` within the [`DataFrameJoinerTest`](https://github.com/jtablesaw/tablesaw/blob/2ab52b11278b85ff075da67d40d17f80e94fbd41/core/src/test/java/tech/tablesaw/join/DataFrameJoinerTest.java) https://github.com/jtablesaw/tablesaw/blob/2ab52b11278b85ff075da67d40d17f80e94fbd41/core/src/main/java/tech/tablesaw/join/DataFrameJoiner.java#L24 is of type `CategoryColumn` and thus raise a `IllegalArgumentException`.

**Comment by benmccann** [comment]
Thanks. I'll take a look at this and your pull request in about two weeks. I'm currently traveling and don't have good access to a computer. Sent from my mobile

**Comment by agebhar1** [comment]
Thanks for the update @benmccann, there is no hurry. Have a good time.

**Comment by benmccann** [comment]
@agebhar1 I've pushed a few commits. Can you try running the tests again?

I've added support for joining on `CategoryColumn`, so I expect the `DataFrameJoinerTest` will pass for you now. However, the column in the test should have been a `DateColumn` instead of a `CategoryColumn`. I've added a new test that checks that the CSV is read correctly. I'm wondering if this new test will fail for you. If it does fail, can you provide some additional details about your environment? E.g. what version of Java, OS, etc.

**Comment by agebhar1** [comment]
Thank you @benmccann for your effort. The `DataFrameJoinerTest` now pass but unfortunately the `CsvReaderTest#testDataTypeDetection3` fails with:
```
Tests run: 13, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 0.073 sec <<< FAILURE!
testDataTypeDetection3(tech.tablesaw.io.csv.CsvReaderTest)  Time elapsed: 0.009 sec  <<< FAILURE!
java.lang.AssertionError: expected:<LOCAL_DATE> but was:<CATEGORY>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at tech.tablesaw.io.csv.CsvReaderTest.testDataTypeDetection3(CsvReaderTest.java:135)
        [...]
```

While debugging each step I found the reason for the failing test(s). The problem arises at 
https://github.com/jtablesaw/tablesaw/blob/2c3931919f3f4f1fd13a5d505a386bc3d7f52fd8/core/src/main/java/tech/tablesaw/io/csv/CsvReader.java#L487
For each supported type the current value is tested to be a valid one. The test for `Date` is
https://github.com/jtablesaw/tablesaw/blob/2c3931919f3f4f1fd13a5d505a386bc3d7f52fd8/core/src/main/java/tech/tablesaw/io/csv/CsvReader.java#L114-L122

The following is evaluated within the JShell (copy and paste in `/edit` window)
```
import java.time.format.*;
import java.time.LocalDate;
DateTimeFormatter dtf1 = DateTimeFormatter.ofPattern("yyyyMMdd");
DateTimeFormatter dtf2 = DateTimeFormatter.ofPattern("MM/dd/yyyy");
DateTimeFormatter dtf3 = DateTimeFormatter.ofPattern("MM-dd-yyyy");
DateTimeFormatter dtf4 = DateTimeFormatter.ofPattern("MM.dd.yyyy");
DateTimeFormatter dtf5 = DateTimeFormatter.ofPattern("yyyy-MM-dd");
DateTimeFormatter dtf6 = DateTimeFormatter.ofPattern("yyyy/MM/dd");
DateTimeFormatter dtf7 = DateTimeFormatter.ofPattern("dd/MMM/yyyy");
DateTimeFormatter dtf8 = DateTimeFormatter.ofPattern("dd-MMM-yyyy");
DateTimeFormatter dtf9 = DateTimeFormatter.ofPattern("M/d/yyyy");
DateTimeFormatter dtf10 = DateTimeFormatter.ofPattern("M/d/yy");
DateTimeFormatter dtf11 = DateTimeFormatter.ofPattern("MMM/dd/yyyy");
DateTimeFormatter dtf12 = DateTimeFormatter.ofPattern("MMM-dd-yyyy");
DateTimeFormatter dtf13 = DateTimeFormatter.ofPattern("MMM/dd/yy");
DateTimeFormatter dtf14 = DateTimeFormatter.ofPattern("MMM-dd-yy");
DateTimeFormatter dtf15 = DateTimeFormatter.ofPattern("MMM/dd/yyyy");
DateTimeFormatter dtf17 = DateTimeFormatter.ofPattern("MMM-dd-yy");
DateTimeFormatter dtf16 = DateTimeFormatter.ofPattern("MMM/d/yyyy");
DateTimeFormatter dtf18 = DateTimeFormatter.ofPattern("MMM dd, yyyy");
DateTimeFormatter dtf19 = DateTimeFormatter.ofPattern("MMM d, yyyy");
DateTimeFormatter DATE_FORMATTER =new DateTimeFormatterBuilder().appendOptional(dtf1).appendOptional(dtf2).appendOptional(dtf2).appendOptional(dtf3).appendOptional(dtf4).appendOptional(dtf5).appendOptional(dtf6).appendOptional(dtf7).appendOptional(dtf8).appendOptional(dtf9).appendOptional(dtf10).appendOptional(dtf11).appendOptional(dtf12).appendOptional(dtf13).appendOptional(dtf14).appendOptional(dtf15).appendOptional(dtf16).appendOptional(dtf17).appendOptional(dtf18).appendOptional(dtf19).toFormatter();

System.getenv("LANG");
System.getenv("LANGUAGE");
LocalDate.parse("Dec 1, 2017", DATE_FORMATTER);
```

With my current environment the output is.
```
$23 ==> "de_DE.UTF8"
$24 ==> "de_DE"
|  java.time.format.DateTimeParseException thrown: Text 'Dec 1, 2017' could not be parsed, unparsed text found at index 0
|        at DateTimeFormatter.parseResolved0 (DateTimeFormatter.java:1991)
|        at DateTimeFormatter.parse (DateTimeFormatter.java:1890)
|        at LocalDate.parse (LocalDate.java:428)
|        at (#25:1)
```
If I switch the locale to `en_US`:
```
$23 ==> "en_US.UTF8"
$24 ==> "en_US"
$25 ==> 2017-12-01
```
If I force locale `US`, then it parses the date successfully:
```
LocalDate.parse("Dec 1, 2017", DATE_FORMATTER.withLocale(Locale.US));
$25 ==> 2017-12-01
```
The German month abbreviation should be 'Dez.':
```
LocalDate.parse("Dez. 01, 2017", DateTimeFormatter.ofPattern("MMM dd, yyyy").withLocale(Locale.GERMANY));
$26 ==> 2017-12-01
```

**Comment by benmccann** [comment]
Great! Thanks for debugging this!

I've simply removed that test since it was only added to determine what was going wrong. Now all the tests should pass again regardless of language.

**Comment by agebhar1** [comment]
@benmccann all tests pass now. I suggest to extend the `DataFrameReader` with a locale option, such that parsing is independent of the system environment. The `DateColumn` already support a locale:
https://github.com/jtablesaw/tablesaw/blob/2c3931919f3f4f1fd13a5d505a386bc3d7f52fd8/core/src/main/java/tech/tablesaw/api/DateColumn.java#L389-L406
What did you think?

**Comment by benmccann** [comment]
@agebhar1 I've filed https://github.com/jtablesaw/tablesaw/issues/224 to track this
