### ISSUE TITLE
Cannot use SKIP in columnTypes, when no header is present

### ISSUE THREAD

**Issue by cc-cpo** [jtablesaw/tablesaw#240]
Hello,

I encountered a problem when reading a file with the following structure not providing a header line:
date, id, method, remote_addr, request_path

The column type used were explicitly defined using this:
ColumnType[] types = {ColumnType.LOCAL_DATE, ColumnType.SKIP, ColumnType.CATEGORY, ColumnType.SKIP, ColumnType.SKIP};

Error:

> Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
> 	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
> 	at java.util.ArrayList.get(ArrayList.java:429)
> 	at tech.tablesaw.api.Table.column(Table.java:283)
> 	at tech.tablesaw.io.csv.CsvReader.read(CsvReader.java:207)
> 	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:63)
> 	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:59)
> 	at TreefinLoad.main(TreefinLoad.java:19)

This test reproduces the problem:
```
    @Test
    public void testWithColumnSKIPWithoutHeader() throws Exception {
        // Read the CSV file
        Table table = Table.read().csv(CsvReadOptions
            .builder("../data/bus_stop_noheader_test.csv")
            .header(false)
            .columnTypes(bus_types_with_SKIP));

        assertEquals(4, table.columnCount());
        // Look at the column names
        assertEquals("[C0, C1, C3, C4]", table.columnNames().toString());
    }
```

**Comment by cc-cpo** [comment]
fixed on master
