### ISSUE TITLE
Index (1) is greater than or equal to list size (1)

### ISSUE THREAD

**Issue by PrimaryKey3610** [jtablesaw/tablesaw#248]
```   
private static final Table ONE_YEAR = Table.read().csv(
            "Date,1 Yr Treasury Rate\n"
                    + "\"Nov 1 2017\",1.65%\n"
                    + "\"Nov 1 2017\",1.56%\n"
                    + "\"Nov 1 2017\",1.40%\n"
                    + "\"Sep 1 2017\",1.28%\n"
                    + "\"Aug 1 2017\",1.23%\n"
                    + "\"Jul 1 2017\",1.22%\n",
            "1 Yr Treasury Rate");

    private static final Table SP500 = Table.read().csv(
            "Date,S&P 500\n"
                    + "\"Nov 1 2017\",2579.36\n"
                    + "\"Nov 1 2017\",2521.20\n"
                    + "\"Nov 1 2017\",2474.42\n"
                    + "\"Aug 1 2017\",2477.10\n"
                    + "\"Jul 1 2017\",2431.39\n"
                    + "\"Jun 1 2017\",2430.06\n",
            "S&P 500");
```
```
 Table joined = SP500.join("Date").inner(ONE_YEAR, "Date");
```
```
java.lang.IndexOutOfBoundsException: Index (1) is greater than or equal to list size (1)

	at it.unimi.dsi.fastutil.ints.IntArrayList.getInt(IntArrayList.java:261)
	at tech.tablesaw.api.CategoryColumn.get(CategoryColumn.java:196)
	at tech.tablesaw.api.CategoryColumn.getString(CategoryColumn.java:153)
	at tech.tablesaw.api.Table.get(Table.java:392)
	at tech.tablesaw.join.DataFrameJoiner.crossProduct(DataFrameJoiner.java:117)
	at tech.tablesaw.join.DataFrameJoiner.inner(DataFrameJoiner.java:74)

```

**Comment by benmccann** [comment]
Thanks for reporting. We didn't handle duplicate keys. I've fixed that here: https://github.com/jtablesaw/tablesaw/commit/62cb872f56c599dd405ad2c18acdb18581a3fd41
