### ISSUE TITLE
Date/time formatter 

### ISSUE THREAD

**Issue by ratulmukh** [jtablesaw/tablesaw#250]
Hi! I am trying to parse a CSV file that has columns containing date/time. But looks like it is failing because the format is not being recognized. Is there a way to pass in a date/time format when setting the column type to LOCAL_DATE_TIME or the other related variants?

**Comment by lwhite1** [comment]
No, but there should be

**Comment by lwhite1** [comment]
This would be very valuable, as there is no telling what kinds of crap source systems might provide in terms of dates formats. It's a regular issue for me. 

If it were implemented well, it would also have the side effect of improving CSV parsing performance, because we could bypass the datetime format selection process when the format was provided. 

I would add up to three additional elements to the read().csv() code, one each for date-time, time, and date. It's not too much to ask that all the dates in the source use the same format.

**Comment by d-spirov** [comment]
How about adding property to the ColumnType, so for each column of these three types there would be option to specify format? This would be optional, with the fallback as it is now.

**Comment by lwhite1** [comment]
If you add it to columnType, you could format data for output. I think @benmccann has an issue open for adding support for currency, for example. 

For handling unusual date-time strings at import, it should go on read().csv().  Something like this might work: 
`read().csv("filename").dateFormat("YYYY-MMM-DD").dateTimeFormat("YYYY/DD/MM: HH:mm) `

**Comment by mark27q1** [comment]
Hello.

Where did this issue get to in the end? I see changes to add the dateFormat functions to the CsvReadOptions.Builder class, but nothing in Table.read().csv() actually references those options. In other words the code to construct the DateTimeFormatter needed to parse an unusual date format is in place but code to use that DateTimeFormatter seems not to be.

Looking at DateColumn.java I see that there is an internal variable called selectedFormatter which is checked before parsing a date column and if null, a default Formatter is created. But there is no code to ever set this selectedFormatter variable except to set it to a default value in the case it is found to be null. So it is _always_ found to be null and replaced with a default formatter. The net effect of which is that although you can specify a date format, tablesaw can't actually use that specified format.

I want to process securities price files in the format used by the MetaTrader software platform. Metatrader uses a CSV format consisting of date, time, open, high, low, close. The date format is yyyy.MM.dd ie dots to separate the fields, which is not one of the default configurations. 

I've worked around it for now by modifying my local copy of TableSaw to add my required format to the list of supported formats by the default date formatter, but I think it would be nice to get this specified-format code working as the docs say it does. Is anyone working on that -- and if not, how would you feel about me having a go?

**Comment by benmccann** [comment]
@mark27q1 you can call `Table.read().csv(CsvReadOptions.Builder options)`

**Comment by mark27q1** [comment]
@benmccann thanks for replying.

That is exactly what I was doing, specifically (in some simple test code):

`        try {

            ColumnType[] types = {LOCAL_DATE, LOCAL_TIME, NUMBER, NUMBER, NUMBER, NUMBER};

            t = Table.read().csv(CsvReadOptions.builder("GBPNZD1M_Bid_XM.csv").header(false).columnTypes(types).dateFormat("yyyy.MM.dd"));

        } catch (IOException e) {

            e.printStackTrace();

            System.exit(1);

        }
`

In a file where the date field (first field is yyyy.MM.dd that is for example 2010.01.04), this blows up with an exception relating to not being able to parse the date (I can get you the precise exception if needed). I spent a chunk of yesterday digging through the code (wasn't familiar with Tablesaw until a couple of days ago) and found that while CsvReadOptions.builder has all the code needed to accept and process the dateFormat call, and stands ready to supply a suitable DateTimeFormatter if asked, CsvReader.read() never asks for it. In the end in DateColumn.convert() the selectedFormatter member variable I referred to above is referenced without ever having been set, resulting in a default formatter being used instead of the one requested. Nothing ever sets that selectedFormatter member variable, except setting it to the default in response to finding it is not already set, so nothing can ever actually control what formatter is used. The syntax you mentioned in your comment makes it possible to _ask_ for it to be used, but nothing pays any attention to the request. Or so it seems to me.

**Comment by benmccann** [comment]
Oops, sorry. I didn't read closely enough the first time

@lwhite1 looks like you may have accidentally added an unused CSV reading option in https://github.com/jtablesaw/tablesaw/pull/260. The option as it currently stands in `CsvReadOptions` maybe should be changed because if the CSV has multiple columns with different date formats that wouldn't be supported by the current API.

**Comment by mark27q1** [comment]
OK I'm a little confused now. Does this mean that the feature is not actually supposed to be implemented in the master branch yet? That the configuration code made it in by mistake and the actual implementation hasn't been done, presumably because of the discussion of using parameterised ColumnTypes? 

If so... back to my original question. Is anyone working on that? 

Thanks! And by the way, I've started working on a project to leverage Tablesaw to support migrating a project I started in python using pandas, to Java so I can get better concurrency. Loving it so far!

**Comment by lwhite1** [comment]
I will get to this sometime int the next week. Sorry, it's taking so long.
I'm pretty busy with work these days.

**Comment by mark27q1** [comment]
Thanks @lwhite1 , in the meantime I modified TypeUtils.java to include my required date format in the list of default supported types, and that allowed me to keep working. I don't suggest that is a suitable solution of course, it just let me keep going while a solution to allow user-specified formats is worked on.

I'm willing to have a crack at an implementation of user-defined date formats if no one else has time, but like you I have a demanding day job and it may be a while until I am able to get something suitable for consideration for inclusion. 

My early impressions of using Tablesaw once I get used to the syntax are that it is impressively fast. Great work guys!

**Comment by lwhite1** [comment]
@mark27q1 Thanks for the kind words, and the offer to help. I've got this almost working and will finish it today.

**Comment by mark27q1** [comment]
Unfortunately not, I'm afraid. I get the precise same exception when processing a data file for the popular MetaTrader 4 retail trading package (I updated my copy of the tablesaw source today following your commits over the last 24 hours or so):

Exception in thread "main" tech.tablesaw.io.csv.AddCellToColumnException: Error while adding cell from row 0 and column C0(position:0): Text '2010.01.04' could not be parsed, unparsed text found at index 0
	at tech.tablesaw.io.csv.CsvReader.read(CsvReader.java:223)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:62)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:58)
	at net.mark_fletcher.rps.TableSawTest.main(TableSawTest.java:29)
Caused by: java.time.format.DateTimeParseException: Text '2010.01.04' could not be parsed, unparsed text found at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1952)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.LocalDate.parse(LocalDate.java:400)
	at tech.tablesaw.api.DateColumn.convert(DateColumn.java:364)
	at tech.tablesaw.api.DateColumn.appendCell(DateColumn.java:371)
	at tech.tablesaw.api.DateColumn.appendCell(DateColumn.java:58)
	at tech.tablesaw.io.csv.CsvReader.read(CsvReader.java:221)
	... 3 more

You'll note the soft brown stuff collides with the whirling blades in DateColumn.convert() method, when it attempts to parse the date using the default date formatter. And, as I mentioned in my earlier comments in this thread, that happens because the DateColumn never gets its selectedFormatter field set to anything in response to the user having selected a date format.

Here are the first few lines of the data file I am trying to import:
2002.01.02,06:33:00,3.49680,3.49870,3.49680,3.49870
2002.01.02,06:44:00,3.49870,3.49870,3.48010,3.48060
2002.01.02,06:45:00,3.48060,3.48150,3.48060,3.48150
2002.01.02,06:46:00,3.48150,3.48280,3.48150,3.48280
2002.01.02,06:47:00,3.48280,3.48280,3.48230,3.48230

You'll note there is no header and the date and time are in separate columns, with the date in yyyy.MM.dd format and the time in HH:mm:ss format (which Tablesaw has no problem with). The four remaining columns are open, high, low and close prices and the overall data is 1-minute price data for the GBPNZD currency pair from early 2002. Tablesaw blows up on the very first line.

The code I used to parse this is quoted earlier in this thread. If I remove both the dateFormat call and the columnTypes call, the file parses without error but the first column is imported as a String. Any other combination (both calls included, or one included without the other) results in the exception I quoted at the beginning of this post.

I can continue to get around it by modifying TypeUtils.java to include yyyy.MM.dd in the supported default formats, but I continue not to suggest that that is a permanent solution. Can this be re-opened? I think the dateFormat option needs to be communicated to DateColumn somehow when the column is being created, and the current code does not do that.

**Comment by lwhite1** [comment]
sorry, only tested to see if detectColumnTypes was working. Will fix this
tonight probably, or tomorrow otherwise.

**Comment by lwhite1** [comment]
I believe this is now (really) fixed. Please lmk if it's still a problem. I
will test further tomorrow, but initial tests suggest it works.

**Comment by komaladke** [comment]
I am facing an blocker while adding very similar date formats.
Issue raised at link : https://github.com/jtablesaw/tablesaw/pull/256#issuecomment-1427807316
Please have a look.
