### ISSUE TITLE
Error loading spambase.csv

### ISSUE THREAD

**Issue by benmccann** [jtablesaw/tablesaw#409]
Loading the file https://datahub.io/machine-learning/spambase/r/spambase.csv no longer works on tablesaw 0.30.0

```
tech.tablesaw.io.csv.AddCellToColumnException: Error while adding cell from row 1449 and column word_freq_cs(position:40): Error adding value to column word_freq_cs: For input string: "0.1"
	at tech.tablesaw.io.csv.CsvReader.addRows(CsvReader.java:244)
	at tech.tablesaw.io.csv.CsvReader.read(CsvReader.java:156)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:62)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:58)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:34)
	at tech.tablesaw.io.DataFrameReader$csv.call(Unknown Source)
	at this cell line 2
	at com.twosigma.beakerx.groovy.evaluator.GroovyCodeRunner.runScript(GroovyCodeRunner.java:94)
	at com.twosigma.beakerx.groovy.evaluator.GroovyCodeRunner.call(GroovyCodeRunner.java:59)
	at com.twosigma.beakerx.groovy.evaluator.GroovyCodeRunner.call(GroovyCodeRunner.java:32)
Caused by: java.lang.NumberFormatException: Error adding value to column word_freq_cs: For input string: "0.1"
	at tech.tablesaw.api.ShortColumn.appendCell(ShortColumn.java:352)
	at tech.tablesaw.api.ShortColumn.appendCell(ShortColumn.java:27)
	at tech.tablesaw.io.csv.CsvReader.addRows(CsvReader.java:242)
	at tech.tablesaw.io.csv.CsvReader.read(CsvReader.java:156)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:62)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:58)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:34)
	at tech.tablesaw.io.DataFrameReader$csv.call(Unknown Source)
```

**Comment by benmccann** [comment]
This column is mostly 0, but 2.3% of the values are non-zero. I'm guessing `detectColumnTypes` is seeing mostly 0 and deciding it should be a short column. I think the regression was caused by the re-introduction of short columns. I was probably using a version that only had double types before and so everything would have worked in that case

I could turn off sampling, which would address the issue, but I also wonder if there's something we shouldn't do to make the sampling a little more sensitive? Right now we only look at 1% of records. We could look at the first 10,000 rows before we start sampling and/or we could look at 5% of records, etc. @lwhite1 thoughts?

**Comment by lwhite1** [comment]
If we do a lot more sampling, it has a lot less benefit, but there’s
probably room for improvement. you could increase the current value of n
for looking at the first n.  That’s the first step in the sampling
algorithm, iirc, so it should be easy.  10k is probably fine.

**Comment by benmccann** [comment]
Ok, thanks. I made that change and it fixes this file
