### ISSUE TITLE
Teradata date format support

### ISSUE THREAD

**Issue by rexshihaoren** [jtablesaw/tablesaw#414]
Exception in thread "main" java.lang.IllegalArgumentException: Cannot append java.sql.Date to DateColumn
	at tech.tablesaw.api.DateColumn.appendObj(DateColumn.java:358)
	at tech.tablesaw.api.DateColumn.appendObj(DateColumn.java:54)
	at tech.tablesaw.io.jdbc.SqlResultSetReader.read(SqlResultSetReader.java:105)
	at tech.tablesaw.io.DataFrameReader.db(DataFrameReader.java:66)

**Comment by benmccann** [comment]
@rexshihaoren can you share some more details or a way for us to reproduce? What format is the teradata date in?

**Comment by rexshihaoren** [comment]
@benmccann sure, I was able to reproduce with a simple example below.
- In Teradata, create a sample table with column in Date format
``` SQL
CREATE MULTISET TABLE sample_db.tbl_employee
( emp_id INT,
 emp_name VARCHAR(20),
created_date DATE FORMAT 'YYYY-MM-DD' NOT NULL
);
INSERT INTO sample_db.tbl_employee (1,'sample_name', '2018-08-08');

```

-  In Java, try to access this table with the following code
``` JAVA
Connection con = DriverManager.getConnection(url, sUser, sPassword);
Statement stmt = con.createStatement();
ResultSet rSet = stmt.executeQuery("SELECT * from sample_db.tbl_employee;");
Table tb = Table.read().db(rSet, "sample");
tb.printAll();
```
This will cause error:
```
java.lang.IllegalArgumentException: Cannot append java.sql.Date to DateColumn
	at tech.tablesaw.api.DateColumn.appendObj(DateColumn.java:358)
	at tech.tablesaw.api.DateColumn.appendObj(DateColumn.java:54)
	at tech.tablesaw.io.jdbc.SqlResultSetReader.read(SqlResultSetReader.java:105)
	at tech.tablesaw.io.DataFrameReader.db(DataFrameReader.java:66)
...
```
