### ISSUE TITLE
Error adding value to column duration: Value out of range. Value:"58329" Radix:10

### ISSUE THREAD

**Issue by LukeWang163** [jtablesaw/tablesaw#424]
Thanks for the great work~
I`ve met with a weird error that is supposed to be fixed in #83 
I was tring to read a csv file from my laptop(windows10, jdk8 and tablesaw-core-0.30.1). The dataset is part of KDD99(https://drive.google.com/open?id=10NN3kABNiXrO1dORTPS7SMfeHXN2HvH3).
Values of the first column 'duration'  are mainly 0s, and some of the values are of type INT instead of SHORT. But while reading the csv, TableSaw recognize the column as Short.

Table originalTable = Table.read().csv("E:/KDD99/kdd_small.csv");

Exception in thread "main" tech.tablesaw.io.csv.AddCellToColumnException: Error while adding cell from row 103875 and column duration(position:0): Error adding value to column duration: Value out of range. Value:"58329" Radix:10
	at tech.tablesaw.io.csv.CsvReader.addRows(CsvReader.java:244)
	at tech.tablesaw.io.csv.CsvReader.read(CsvReader.java:156)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:62)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:58)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:34)
        at ...
Caused by: java.lang.NumberFormatException: Error adding value to column duration: Value out of range. Value:"58329" Radix:10
	at tech.tablesaw.api.ShortColumn.appendCell(ShortColumn.java:352)
	at tech.tablesaw.api.ShortColumn.appendCell(ShortColumn.java:27)
	at tech.tablesaw.io.csv.CsvReader.addRows(CsvReader.java:242)
	... 5 more

**Comment by lwhite1** [comment]
You can specify the column types in the import reader. There's a description of how on this page: https://jtablesaw.github.io/tablesaw/userguide/importing_data.  You can also turn off the sampling used in type detection so that it will see all the values.

**Comment by benmccann** [comment]
That's probably a good idea. Perhaps that method could be changed to take `CsvReadOptions`

**Comment by LukeWang163** [comment]
> That's probably a good idea. Perhaps that method could be changed to take `CsvReadOptions`

You are right! Thank you for replying

**Comment by care1e55** [comment]
Have the same issue. Had to remove ".minimizeColumnSizes()" option for stability
