### ISSUE TITLE
Error when converting to Smile AttributeDataset

### ISSUE THREAD

**Issue by LukeWang163** [jtablesaw/tablesaw#427]
Thanks for the great work! 
I`ve encountered some problem when converting Table to Smile AttributeDataset.
1.
[heartdisease.txt](https://github.com/jtablesaw/tablesaw/files/2685130/heartdisease.txt)
Here is my testing dataset.
```
Table originalTable = Table.read().csv("heartdisease.txt");
AttributeDataset attributeDataset = originalTable.smile().nominalDataset("status", "age", "trestbps", "chol", "thalach", "oldpeak", "ca");
```

I set status as reponseColName which is a nominal variable, and six other numeric columns as variablesColNames. Then I ran into IndexOutOfBoundsException as below.

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index (303) is greater than or equal to list size (303)
	at it.unimi.dsi.fastutil.shorts.ShortArrayList.getShort(ShortArrayList.java:267)
	at tech.tablesaw.api.ShortColumn.getDouble(ShortColumn.java:296)
	at tech.tablesaw.conversion.SmileConverter.lambda$dataset$4(SmileConverter.java:77)
	at java.util.stream.ReferencePipeline$6$1.accept(ReferencePipeline.java:244)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.DoublePipeline.toArray(DoublePipeline.java:506)
	at tech.tablesaw.conversion.SmileConverter.dataset(SmileConverter.java:77)
	at tech.tablesaw.conversion.SmileConverter.nominalDataset(SmileConverter.java:66)

My dataset has 303 rows. The values of x are correct, but the size of y expanded to 606. I traced a bit, and found that it first appended 303 missingValueIndicators, then appended 303 real values. It`s weird.

2. I wonder how to convert nominal or string columns to AttributeDataset. Or is that possible to add  a preprocessing function that maps string values to doubles and then convert as numeric column( just like LabelEncoder() in python sklearn https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html#sklearn.preprocessing.LabelEncoder )

3. When I test with tablesaw/core/src/test/java/tech/tablesaw/conversion/SmileConverterTest.java to convert 'moneyball' dataset to AttributeDataset, the conversion was a success. But when I want to print the response of the AttributeDataset, it ran into IllegalArgumentException
Exception in thread "main" java.lang.IllegalArgumentException: Invalid nominal value: 0.0
	at smile.data.NominalAttribute.toString(NominalAttribute.java:191)
	at smile.data.AttributeVector.toString(AttributeVector.java:138)
	at smile.data.AttributeVector.head(AttributeVector.java:102)
	at smile.data.AttributeVector.toString(AttributeVector.java:95)
	at java.lang.String.valueOf(String.java:2994)
	at java.io.PrintStream.println(PrintStream.java:821)

The code I used:
```
Table originalTable = Table.read().csv("E:/KDD99/baseball.csv");
AttributeDataset attributeDataset = originalTable.smile().nominalDataset("Playoffs", "RS", "RA", "OBP");
System.out.println(attributeDataset.response());
```

It can be print out when I use `DelimitedTextParser` to parse the csv file to `AttributeDataset`.
Thanks very much!

**Comment by lwhite1** [comment]
what version are you using?

Are there 606 values in originalTable, or only after the conversion to
AttributeDataset?

thanks.

**Comment by lwhite1** [comment]
This is likely a case where a column or similar object is initialized to a certain size and filled with missing values, and then appended to, when it should be using a method like set(x, value).  It can probably be fixed by either not prefilling with missing, or not appending, whichever is best for the setting. 

I'm not sure at present where it's happening though so it may take a little time to fix.

**Comment by benmccann** [comment]
Thanks @lwhite1 for fixing this! I'm going to close this issue now

I've sent an additional enhancement in https://github.com/jtablesaw/tablesaw/pull/429

**Comment by lwhite1** [comment]
I don't think this is completely fixed. You can still get an exception printing the smile object because we're forcing the data to be numeric even when the Smile type is nominal. 

I didn't have a chance to figure out the fix yet.

**Comment by benmccann** [comment]
The issue was slightly different. I pushed a fix with a corresponding test here: https://github.com/jtablesaw/tablesaw/commit/e366acd058e07478a68834a6985b79194fb2af98

**Comment by benmccann** [comment]
`AttributeDataset.add` only supports numerics, which is why we must do the forced conversion. It would be nice if it supported strings, but we'd need to file a feature request with Smile for that

**Comment by benmccann** [comment]
@lwhite1 I consider the issue you found to be a bug in Smile. My commit is a workaround. I've also filed a bug with Smile to see if we can address it there as well: https://github.com/haifengl/smile/issues/397

**Comment by benmccann** [comment]
I added better handling of Tablesaw String -> Smile nominal. I think we should be pretty good now

@LukeWang163 I'd love for you to give it another try and let me know if you have any feedback. I just cut a new release with a number of improvements: https://github.com/jtablesaw/tablesaw/releases/tag/v0.30.2
