### ISSUE TITLE
NPE When Using Table.read().csv()

### ISSUE THREAD

**Issue by lewisdawson** [jtablesaw/tablesaw#443]
Using a super basic example provided on tablesaw page I ran across, I get a NPE:

```
        String location =
                "https://raw.githubusercontent.com/jtablesaw/tablesaw/master/data/bush.csv";
        try (InputStream input = new URL(location).openStream()) {
            Table table = Table.read().csv(input, "test"); // <-- line 39 in stack trace
            Plot.show(TimeSeriesPlot.create("Fox approval ratings", table, "date", "approval"));
        }
```

```
Exception in thread "main" java.lang.NullPointerException
	at java.io.FileInputStream.<init>(FileInputStream.java:130)
	at tech.tablesaw.io.csv.CsvReader.getColumnTypes(CsvReader.java:208)
	at tech.tablesaw.io.csv.CsvReader.read(CsvReader.java:121)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:62)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:58)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:50)
	at com.example.main(Test.java:39)
```

**Comment by lwhite1** [comment]
where exactly did you find this code?

**Comment by lwhite1** [comment]
this logic is broken:

```
    private ColumnType[] getColumnTypes(CsvReadOptions options, byte[] bytes) throws IOException {
        ColumnType[] types;
        Preconditions.checkNotNull(options, "Read options cannot be null.");

        try(InputStream detectTypesStream = options.reader() != null
                ? new ByteArrayInputStream(bytes)
                : new FileInputStream(options.file())) {
            types = detectColumnTypes(detectTypesStream, options);
        }
        return types;
    }

```
The try-with-resources condition assumes that if you don't have a reader, you have a file. You can have an inputStream opened on a URL without having a reader.

**Comment by lwhite1** [comment]
fixed

**Comment by benmccann** [comment]
I've released a new version with this fix
