### ISSUE TITLE
Best way to consume large data set

### ISSUE THREAD

**Issue by DareUrDream** [jtablesaw/tablesaw#447]
Hi,

I am trying to read a file which have 1 million rows and 7 column. But when I get the below exception.

> Exception in thread "main" com.univocity.parsers.common.TextParsingException: java.lang.ArrayIndexOutOfBoundsException - 10000
Hint: Number of columns processed may have exceeded limit of 10000 columns. Use settings.setMaxColumns(int) to define the maximum number of columns your input can have
Ensure your configuration is correct, with delimiters, quotes and escape sequences that match the input format you are trying to parse
Parser Configuration: CsvParserSettings:
	Auto configuration enabled=true
	Autodetect column delimiter=false
	Autodetect quotes=false
	Column reordering enabled=true
	Delimiters for detection=null
	Empty value=null
	Escape unquoted values=false
	Header extraction enabled=null
	Headers=null
	Ignore leading whitespaces=true
	Ignore leading whitespaces in quotes=false
	Ignore trailing whitespaces=true
	Ignore trailing whitespaces in quotes=false
	Input buffer size=1048576
	Input reading on separate thread=true
	Keep escape sequences=false
	Keep quotes=false
	Length of content displayed on error=-1
	Line separator detection enabled=false
	Maximum number of characters per column=4096
	Maximum number of columns=10000
	Normalize escaped line separators=true
	Null value=null
	Number of records to read=all
	Processor=none
	Restricting data in exceptions=false
	RowProcessor error handler=null
	Selected fields=none
	Skip bits as whitespace=true
	Skip empty lines=true
	Unescaped quote handling=nullFormat configuration:
	CsvFormat:
		Comment character=#
		Field delimiter=,
		Line separator (normalized)=\n
		Line separator sequence=\n
		Quote character="
		Quote escape character="
		Quote escape escape character=null
Internal state when error was thrown: line=0, column=10001, record=0, charIndex=42101
	at com.univocity.parsers.common.AbstractParser.handleException(AbstractParser.java:369)
	at com.univocity.parsers.common.AbstractParser.parseNext(AbstractParser.java:595)
	at tech.tablesaw.io.csv.CsvReader.detectColumnTypes(CsvReader.java:472)
	at tech.tablesaw.io.csv.CsvReader.getColumnTypes(CsvReader.java:209)
	at tech.tablesaw.io.csv.CsvReader.read(CsvReader.java:121)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:62)
	at com.cisco.evaluate.tablesaw.TablesawTestMain.startEvaluation(TablesawTestMain.java:30)
	at com.cisco.evaluate.tablesaw.TablesawTestMain.main(TablesawTestMain.java:18)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 10000
	at com.univocity.parsers.common.ParserOutput.valueParsed(ParserOutput.java:327)
	at com.univocity.parsers.csv.CsvParser.parseRecord(CsvParser.java:176)
	at com.univocity.parsers.common.AbstractParser.parseNext(AbstractParser.java:560)
	... 6 more

Then I use the CsvReadOptions and set "maxNumberOfColumns(1000000*8)"  and use that object for reading the csv, which then ends up with no records in memory.

`CsvReadOptions csvReadOptions = CsvReadOptions.builder("./src/main/resources/XYZ_XYZ.csv").header(true).maxNumberOfColumns(1000000*8).build(); Table asdTable = Table.read().csv(csvReadOptions).retainColumns("XYZ", "ABCDE");`

Exception in thread "main" java.lang.IllegalStateException: Column <XYZ> does not exist in table <XYZ_XYZ>.csv
	at tech.tablesaw.table.Relation.column(Relation.java:115)
	at tech.tablesaw.joining.DataFrameJoiner.<init>(DataFrameJoiner.java:63)
	at tech.tablesaw.api.Table.join(Table.java:906)
	at com.cisco.evaluate.tablesaw.TablesawTestMain.startEvaluation(TablesawTestMain.java:34)
	at com.cisco.evaluate.tablesaw.TablesawTestMain.main(TablesawTestMain.java:18)

I intent to left join these rows with another table having 10K records. What should I do to get my data? 

Cheers,
DareUrDream

**Comment by DareUrDream** [comment]
> Maybe related to recently fixed [84de128#diff-257b402c9aa30f109de73158945b7c64](https://github.com/jtablesaw/tablesaw/commit/84de1286f83fff96572d636975674e16858d2d19#diff-257b402c9aa30f109de73158945b7c64)? Perhaps try on master and see if it works any better

This works. Thanks...

Anything I can do to speed up the time taken for the joins.

**Comment by lwhite1** [comment]
i would do the join manually. it's pretty simple.

- add the columns from the smaller file to the larger. you may want to fill
them with their missing values so you can use set(index, value) to do the
update.
- iterate the larger file and search the smaller for matches, and copy the
matching record into the new columns

you could sort the larger file on the join column(s) and then only repeat
the search when necessary, but how fancy you want to get depends on how
often you need to do this join.

**Comment by lwhite1** [comment]
I'm closing this as it's been a while since there was any discussion. If you still have issues please LMK.
