### ISSUE TITLE
DistributionVisualizations example fails reading csv file

### ISSUE THREAD

**Issue by lwhite1** [jtablesaw/tablesaw#486]
Maybe switch to auto line-ending detection? 

```
Exception in thread "main" com.univocity.parsers.common.TextParsingException: java.lang.ArrayIndexOutOfBoundsException - 10000
Hint: Number of columns processed may have exceeded limit of 10000 columns. Use settings.setMaxColumns(int) to define the maximum number of columns your input can have
Ensure your configuration is correct, with delimiters, quotes and escape sequences that match the input format you are trying to parse
Parser Configuration: CsvParserSettings:
	Auto configuration enabled=true
	Autodetect column delimiter=false
	Autodetect quotes=false
	Column reordering enabled=true
	Delimiters for detection=null
	Empty value=null
	Escape unquoted values=false
	Header extraction enabled=null
	Headers=null
	Ignore leading whitespaces=true
	Ignore leading whitespaces in quotes=false
	Ignore trailing whitespaces=true
	Ignore trailing whitespaces in quotes=false
	Input buffer size=1048576
	Input reading on separate thread=true
	Keep escape sequences=false
	Keep quotes=false
	Length of content displayed on error=-1
	Line separator detection enabled=false
	Maximum number of characters per column=4096
	Maximum number of columns=10000
	Normalize escaped line separators=true
	Null value=null
	Number of records to read=all
	Processor=none
	Restricting data in exceptions=false
	RowProcessor error handler=null
	Selected fields=none
	Skip bits as whitespace=true
	Skip empty lines=true
	Unescaped quote handling=nullFormat configuration:
	CsvFormat:
		Comment character=#
		Field delimiter=,
		Line separator (normalized)=\n
		Line separator sequence=\n
		Quote character="
		Quote escape character="
		Quote escape escape character=null
Internal state when error was thrown: line=0, column=10001, record=0, charIndex=104277
	at com.univocity.parsers.common.AbstractParser.handleException(AbstractParser.java:369)
	at com.univocity.parsers.common.AbstractParser.parseNext(AbstractParser.java:595)
	at tech.tablesaw.io.FileReader.getTypes(FileReader.java:43)
	at tech.tablesaw.io.csv.CsvReader.detectColumnTypes(CsvReader.java:142)
	at tech.tablesaw.io.csv.CsvReader.getReaderAndColumnTypes(CsvReader.java:69)
	at tech.tablesaw.io.csv.CsvReader.read(CsvReader.java:80)
	at tech.tablesaw.io.csv.CsvReader.read(CsvReader.java:76)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:72)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:68)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:44)
	at tech.tablesaw.examples.DistributionVisualizations.main(DistributionVisualizations.java:15)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 10000
	at com.univocity.parsers.common.ParserOutput.valueParsed(ParserOutput.java:327)
	at com.univocity.parsers.csv.CsvParser.parseRecord(CsvParser.java:176)
	at com.univocity.parsers.common.AbstractParser.parseNext(AbstractParser.java:560)
	... 9 more

```

**Comment by benmccann** [comment]
Is the example or CSV file checked in? I'm curious which file it's failing on

**Comment by lwhite1** [comment]
they're both checked in. The code is in the jsplot examples folder in test, and the CSV file is the Sacremento real estate file.

**Comment by benmccann** [comment]
That particular file has `\r` line endings, which is strange

I verified that `settings.setLineSeparatorDetectionEnabled(true);` does fix it
