### ISSUE TITLE
Create Better Column Not Found Error Message for Row

### ISSUE THREAD

**Issue by ryancerf** [jtablesaw/tablesaw#617]
Ran into this today while using the library.

`row.getLong("colDoesNotExist")` throws an NPE. We should create a better error message. Possibly create a custom ColumnNotFoundException (unchecked) and use it project wide.

Current error message:

```
Exception in thread "main" java.lang.NullPointerException
	at tech.tablesaw.api.Row.getLong(Row.java:153)
	at com.ryancerf.tgo.steps.CreateInvoicesStep.createInvoices(CreateInvoicesStep.java:23)
	at com.ryancerf.tgo.Main.main(Main.java:40)
```

This error also occurs when the column name exists on the table, but the type is wrong. It would be nice if we searched the possible column names and gave the user the hint that they probably got the wrong `row.get` method.

If no one has grabbed this I should have time to work on it in a few days.

**Comment by ryancerf** [comment]
Similarly but less important we should consider a better error message for class cast exception that includes the column name.

`table.longColumn.get("myIntColumn")` 

```java
Exception in thread "main" java.lang.ClassCastException: 
tech.tablesaw.api.IntColumn cannot be cast to tech.tablesaw.api.LongColumn
```
