### ISSUE TITLE
“Question”: Getting 'Data type mismatch.' exception reading data from resultset of DB2 type database 

### ISSUE THREAD

**Issue by lusnyaktah** [jtablesaw/tablesaw#685]
I am working with DB2(ibmi) database type. Reading data from result set like this:

`Table db2q = Table.read().db(db2resultSet, "db2q");`

I am getting the following exception
 
``` 
java.sql.SQLException: Data type mismatch.
	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:888)
	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:435)
	at com.ibm.as400.access.SQLCharForBitData.getBoolean(SQLCharForBitData.java:306)
	at com.ibm.as400.access.AS400JDBCResultSet.getBoolean(AS400JDBCResultSet.java:2495)
	at tech.tablesaw.io.jdbc.SqlResultSetReader.read(SqlResultSetReader.java:125)
	at tech.tablesaw.io.DataFrameReader.db(DataFrameReader.java:151)
```

The query contains a column with the following type(getting info from ResultSetMetaData):
type: -2
type name: CHAR () FOR BIT DATA

The tablesaw library converts this char column into boolean. 
Are you going to fix this problem?

**Comment by lusnyaktah** [comment]
I just added translate binary=true in db2 the connection string and it worked.
