### ISSUE TITLE
Inconsistent handling of quotes when reading / writing CSV

### ISSUE THREAD

**Issue by aeberhart** [jtablesaw/tablesaw#771]
I ran into some issues when tables contain quotes. The following test case fails. I used a workaround to replace \\" with "" before reading the output again (see the workaround comment below):

```java
public void preserveQuote() throws IOException {
	
	// test table has 1 row and 1 column with the value "
	Table table = Table.create("test");
	table.addColumns(StringColumn.create("quote", Arrays.asList("\"")));
	
	// write to csv and read again
	Writer writer = new StringWriter();
	table.write().csv(writer);
	String string = writer.toString();
	// workaround
	// string = string.replaceAll("\\\\\"", "\"\"");
	Table out = Table.read().csv(new StringReader(string));
	
	// write - read should preserve the "
	assertEquals(table.get(0, 0), out.get(0, 0));
}
```

If the value is "," instead of a single quote, I get this stack trace:

```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at tech.tablesaw.io.FileReader.parseRows(FileReader.java:117)
	at tech.tablesaw.io.csv.CsvReader.read(CsvReader.java:87)
	at tech.tablesaw.io.csv.CsvReader.read(CsvReader.java:76)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:195)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:191)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:187)
	at tech.tablesaw.io.csv.CsvReaderTest.preserveQuote(CsvReaderTest.java:106)
```

Note sure if this is a tablesaw issue or an issue of the underlying CSV lib.

**Comment by benmccann** [comment]
I don't get an exception on `master`, but the test did fail for me. I sent a fix here: https://github.com/jtablesaw/tablesaw/pull/772

**Comment by aeberhart** [comment]
Thanks for the quick fix!

On master, you do get the exception when the values is "," (comma, surrounded by quotes). Your change fixes this issue too though, so it's all good!
