### ISSUE TITLE
Getting java.security.AccessControlException: access denied 

### ISSUE THREAD

**Issue by Rajatk95** [jtablesaw/tablesaw#809]
Hi,

I am getting` java.security.AccessControlException: access denied ("java.lang.management.ManagementPermission", "monitor")` while reading tabular data from CSV and Resultset.

`Table data = Table.read().db(resultset, "TABLE_NAME");`

```
Caused by: java.security.AccessControlException: access denied ("java.lang. management Management Permission "monitor) 
at java.security.AccessControlContext.checkPermission (AccessControlContext.java:472) 
at java.security.AccessController.checkPermission(AccessController.java:884) 
at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) 
at sun.management. Util.checkAccess(Util.java:77) 
at sun.management.Util.checkMonitorAccess (Util.java:82) 
at sun. management. RuntimeImpl.getInputArguments(RuntimeImpl.java: 108) 
at io.github.classgraph.ModulePathInfo.<init>(ModulePathInfo.java:131) 
at nonapi.io.github.classgraph.scanspec.ScanSpec.<init>(ScanSpec.java: 230) 
at io.github.classgraph.classGraph.<init>(ClassGraph.java:63) 
at tech.tablesaw.api.Table.autoRegisterReadersAndwriters(Table.java:120) 
at tech.tablesaw.api.Table.<clinit>(Table.java:77) 
7 more
```

I know this issue can be fixed by granting the jar appropriate policy something like specified [here](https://docs.oracle.com/cd/E19830-01/819-4726/fxxzk/index.html) but the real question is for why tablesaw requires to access something sensitive as specified [here](https://docs.oracle.com/javase/7/docs/api/java/lang/management/ManagementPermission.html)

Thanks

**Comment by lwhite1** [comment]
Sorry for the very belated reply. What version of Java are you using?

**Comment by Rajatk95** [comment]
java 1.8.0_221

**Comment by lwhite1** [comment]
Thanks. I use 1.8 and 9.0 and haven't seen this issue, probably because I haven't used the SQL API recently. I don't understand the ReaderRegistry code so it will probably be a while before I can really look into this, but it seems like a significant issue and I appreciate your bringing it to our attention.  

FWIW, the registry code addresses a hard problem of how to let people use different kinds of data interfaces without having the core jar be enormous. Anyway, sorry about the issue and thanks again.

**Comment by benmccann** [comment]
I don't think it's related to the sql reader. Rather it looks like it's happening when we register the readers, which we do by scanning the classpath for readers and registering them automatically to make setup easier for users.

I think there's an option to disable the auto-registration that you can use to avoid the error and then manually register any readers you want to use.

I'm not sure why you'd get this error and we don't. Is there anything notable about your setup? E.g. are you running in an application server like weblogic, running a specific JDK distribution like graalvm, etc.?

**Comment by lwhite1** [comment]
I'm going to close this, since there was no follow-up to Ben's question and no one else has reported it. We can reopen if necessary.
