### ISSUE TITLE
Appending Rows to Table

### ISSUE THREAD

**Issue by gmsharpe** [jtablesaw/tablesaw#834]
How do you append a single row to a table?  I've tried instantiating row objects, and 'setting' column and value pairs, but then run into issues appending that data to an existing table.  

```
        List<Pair<String,Long>> counts = new ArrayList<>();
        counts.add(Pair.of("one", "1"));
        tech.tablesaw.api.Table tableCounts =
                tech.tablesaw.api.Table.create("Canvas Data Tables")
                           .addColumns(StringColumn.create("table_name", new ArrayList<String>()),
                                                 StringColumn.create("row_count",new ArrayList<String>()));

        for(Pair<String,Long> result : counts){
            tech.tablesaw.api.Row row = new tech.tablesaw.api.Row(tableCounts);
            row.setString("row_count", result.getRight());
            tableCounts.addRow(row);        
        }
```

The above results in:

```

        java.lang.ArrayIndexOutOfBoundsException: -1
	at it.unimi.dsi.fastutil.bytes.ByteArrayList.set(ByteArrayList.java:311)
	at tech.tablesaw.columns.strings.ByteDictionaryMap.set(ByteDictionaryMap.java:261)
	at tech.tablesaw.api.StringColumn.set(StringColumn.java:273)
	at tech.tablesaw.api.StringColumn.set(StringColumn.java:45)
	at tech.tablesaw.api.Row.setString(Row.java:407)

```

**Comment by lwhite1** [comment]
There's a method called append that takes a Row object. You can set values
in the Row.

LMK if that doesn't work for you.

cheers
