### ISSUE TITLE
Error adding value to column

### ISSUE THREAD

**Issue by ayoubhamaoui** [jtablesaw/tablesaw#857]
I'm trying to import excel file .xlsx that contains 17K row, the program fails because I have a column that starts with 0 and in the middle of the column there is some values type string.

**CODE:**
```
XlsxReadOptions options = XlsxReadOptions.builder("file.xlsx").build();
Table bushTable =  Table.read().usingOptions(options);
System.out.println(bushTable.structure());		
```

**ERROR:**
```
Exception in thread "main" java.lang.NumberFormatException: Error adding value to column PROPUW_roof_anchors: For input string: "X         "
	at tech.tablesaw.api.IntColumn.appendCell(IntColumn.java:365)
	at tech.tablesaw.api.IntColumn.appendCell(IntColumn.java:19)
	at tech.tablesaw.io.xlsx.XlsxReader.appendValue(XlsxReader.java:261)
	at tech.tablesaw.io.xlsx.XlsxReader.createTable(XlsxReader.java:239)
	at tech.tablesaw.io.xlsx.XlsxReader.readMultiple(XlsxReader.java:80)
	at tech.tablesaw.io.xlsx.XlsxReader.read(XlsxReader.java:65)
	at tech.tablesaw.io.xlsx.XlsxReader.read(XlsxReader.java:48)
	at tech.tablesaw.io.DataFrameReader.usingOptions(DataFrameReader.java:139)
	at test.ExcelDataType.echoAsCSV(ExcelDataType.java:60)
	at test.ExcelDataType.main(ExcelDataType.java:71)
```

**Data:**
![image](https://user-images.githubusercontent.com/21150547/104131865-9d4ab800-5379-11eb-87de-8a3f09ca5901.png)

# HANDLING CSV FILE
**Remarque:**
I don't get this kind of error when I convert excel to csv but in my case, for csv file there is another column start with **integers** but in middle, there are some **float** values.
```
Error while adding cell from row 13282 and column Amoun(position:64): Error adding value to column Amount: For input string: "821.53"
```
**Data:**
![image](https://user-images.githubusercontent.com/21150547/104131977-953f4800-537a-11eb-8bf1-697074651cd8.png)

**Comment by lwhite1** [comment]
You can use CSVReadOptions to turn off sampling when you're reading the
file. Then it should see the string before making the decision. Otherwise,
you can specify the types for the columns in an array.

**Comment by ayoubhamaoui** [comment]
Yes it works like a charm! 
Thank you

**Comment by ayoubhamaoui** [comment]
@lwhite1 how about reading excel file directly is there any way to fix the issue
Thanks

**Comment by lwhite1** [comment]
I don't know. I never use the Excel API so enhancing/fixing it isn't a big
priority for me.
