### ISSUE TITLE
Is "Table" Thread safe ?

### ISSUE THREAD

**Issue by helpta** [jtablesaw/tablesaw#858]
**Background:**
    I use "Table" in my mul-thread context

**Desc:**
    some threads change it (remove column 、add or concat other table)
    some thread use it (i.g: use method columnNames() to judge whether a columnName is contain in the Table)

**Question:**
    there will occur an exception "java.util.ConcurrentModificationException"
`
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1390)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at tech.tablesaw.api.Table.columnNames(Table.java:428)
	at tech.tablesaw.api.Table.validateColumn(Table.java:253)
	at tech.tablesaw.api.Table.addColumns(Table.java:239)
	at com.welab.xanfer.othertest.TableTest$1.run(TableTest.java:43)
`

**here is a piece of  test code:**
`public static void main(String[] args) {
        Table table = Table.create();
        for (int i = 0; i < 10; i++) {
            Thread t = new Thread("addColumn-" + i) {
                @Override
                public void run() {
                    for (int index = 0; index < 10; index++) {
                        table.addColumns(StringColumn.create(getName() + "-" + index));
                    }
                }
            };
            t.start();
        }

 for (int i = 0; i < 10; i++) {
            Thread t = new Thread("getColumn-" + i) {
                @Override
                public void run() {
                    System.err.println(getName() + "tableColumnNames>>>" + table.columnNames());
                }
            };
            t.start();
        }
    }
`

**Comment by lwhite1** [comment]
no it isn't

**Comment by helpta** [comment]
Are you saying that Table is not suitable for use in multi-threaded scenarios, or am I using it the wrong way
@lwhite1

**Comment by lwhite1** [comment]
Table was designed for data analysts rather than as a server component so
no attempt was made to make it thread safe.

That said, most methods (not all) return a new table as the result so it
might be possible to use it for some limited applications.

**Comment by helpta** [comment]
OK

Larry White ***@***.***>于2021年1月20日 周三16:17写道：
