### ISSUE TITLE
Pattern.compile(separator()) exception in StorageManager

### ISSUE THREAD

**Issue by rapidark** [jtablesaw/tablesaw#92]
in windows，when i save the table，just the code like this
`
String folder = System.getProperty("user.dir") + File.separator + "tmp/testdata";
String dbName = table.save(folder);
`

it will casue exception, because of Separator in windows is '\' , 

`
java.lang.ExceptionInInitializerError
    at com.github.lwhite1.tablesaw.api.Table.save(Table.java:717)
    at com.github.lwhite1.tablesaw.SymbolTest.testToJson(SymbolTest.java:65)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
 ^
    at java.util.regex.Pattern.error(Pattern.java:1955)
    at java.util.regex.Pattern.compile(Pattern.java:1702)
    at java.util.regex.Pattern.<init>(Pattern.java:1351)
    at java.util.regex.Pattern.compile(Pattern.java:1028)
    at com.github.lwhite1.tablesaw.store.StorageManager.<clinit>(StorageManager.java:55)
    ... 26 more

`

**solution:**
`
  static String separator() {
      // fix Pattern compile exception in windows
      if(!isWindows()) {
        FileSystem fileSystem = FileSystems.getDefault();
        return fileSystem.getSeparator();
      }
      return "\\";
  }

  public static boolean isWindows()
  {
      return System.getProperty("os.name").toLowerCase().startsWith("windows");
  }
`

**Comment by lwhite1** [comment]
I think the (current version) of the code as it is written is supposed to work, but i can't test on a windows machine. 

I don't see the lines: 
    String folder = System.getProperty("user.dir") + File.separator + "tmp/testdata"; 
    String dbName = table.save(folder); 
in the tablesaw code, StorageManager uses the static method separator() which gets the separator from the FileSystem. This change was made to address this specific problem on Windows. It may be that I have not updated maven central since I made the fix so I will do that.

**Comment by rapidark** [comment]
in windows, fileSystem.getSeparator() is \ ,
"Pattern.compile(separator())" will be "Pattern.compile("\")" , result as the error Pattern 
` static String separator() {
	  // fix Pattern compile exception in windows
	  if(!isWindows()) {
	    FileSystem fileSystem = FileSystems.getDefault();
	    return fileSystem.getSeparator();
	  }
	  return "\\\\";
  }`

**Comment by johanra** [comment]
The path separator on windows is a single \ this must be "quoted" before compiling the regexp. See my pull request for a fix.

**Comment by benmccann** [comment]
PR to fix this was merged
