### ISSUE TITLE
UncheckedIOException read only file system error when using plotly in packaged applications

### ISSUE THREAD

**Issue by rossetti** [jtablesaw/tablesaw#946]
I have an application that I built and packaged using the jpackage tool of java 14+. When packaging the app for either windows or mac, I get the following error. It looks like the plot functions are trying to write out to a temporary folder "/testoutput" which is dependent on where the program was invoked.  This will cause a problem when the program is installed.  On the windows side, I install in a directory that I have full read/write privileges, it seems to work.  On the mac side, I have not been able to get a work around.  Where and why is this /testoutput folder being created?  Is there a way to specify its location within the API

java.io.UncheckedIOException: java.nio.file.FileSystemException: /testoutput: Read-only file system
	at tech.tablesaw.plotly.Plot.randomFile(Plot.java:71)
	at tech.tablesaw.plotly.Plot.show(Plot.java:49)
	at arena.ArenaWelchDataFileReader.showWelchPlot(ArenaWelchDataFileReader.java:393)
	at arena.ArenaWelchDataFileReader.showWelchPlot(ArenaWelchDataFileReader.java:332)
	at arena.ArenaWelchDataFileReader.showWelchPlot(ArenaWelchDataFileReader.java:319)
	at gui.CenterView.plotWelchData(CenterView.kt:839)
	at gui.CenterView.access$plotWelchData(CenterView.kt:23)
	at gui.CenterView$root$1$3$14$1$2$3$2$1.invoke(CenterView.kt:525)
	at gui.CenterView$root$1$3$14$1$2$3$2$1.invoke(CenterView.kt:23)
	at tornadofx.AsyncKt$runAsyncWithProgress$3.invoke(Async.kt:248)
	at tornadofx.AsyncKt$runAsyncWithProgress$3.invoke(Async.kt)
	at tornadofx.FXTask.call(Async.kt:457)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.nio.file.FileSystemException: /testoutput: Read-only file system
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
	at java.base/java.nio.file.Files.createDirectory(Files.java:690)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
	at java.base/java.nio.file.Files.createDirectories(Files.java:783)
	at tech.tablesaw.plotly.Plot.randomFile(Plot.java:69)
	... 16 more

**Comment by lwhite1** [comment]
The use of testoutput is intended as a convenience for people doing data analysis interactively in their IDE. It is set along with other. defaults in the Plot class.

```
  private static final String DEFAULT_OUTPUT_FILE = "output.html";
  private static final String DEFAULT_OUTPUT_FOLDER = "testoutput";
```

You can provide an alternative file for any plot using

```
public static void show(Figure figure, File outputFile) {
    show(figure, DEFAULT_DIV_NAME, outputFile);
}
```

You could also provide your own variation on the Plot utility class, which is pretty simple (less than 80 lines, no mutable variables), or use another mechanism for displaying plots, like streaming the generated javascript into a page served dynamically by sparkjava, javalin, or whatever. 

Clearly, this isn't a great design in that there's no way to change the default location, but it has mostly worked for people.

**Comment by rossetti** [comment]
I understand.  I basically worked up a variation of the plot utility class.  I think that an improvement would allow the API to change the default file locations. But, I agree. A work around is pretty easy. Thanks
