### ISSUE TITLE
modula bug

### ISSUE THREAD

**Issue by dddeveloperrr** [jtablesaw/tablesaw#958]
I use jdk 14.

here is my code and the error message:

`package jtablesaw;

import java.io.IOException;
import tech.tablesaw.api.DoubleColumn;
import tech.tablesaw.api.StringColumn;
import tech.tablesaw.api.Table;
import tech.tablesaw.selection.Selection;

public class Main
	{

		public static void main(String[] args) throws IOException
			{
				
				String[] animals = {"bear", "cat", "giraffe"};
				double[] cuteness = {90.1, 84.3, 99.7};
				Table cuteAnimals = Table.create("Cute Animals").addColumns( StringColumn.create("Animal types", animals), DoubleColumn.create("rating", cuteness));
			}
	}
`

`Exception in thread "main" java.lang.ExceptionInInitializerError
	at io.github.classgraph.ScanResult.init(ScanResult.java:214)
	at io.github.classgraph.ClassGraph.<init>(ClassGraph.java:87)
	at tablesaw.core@0.38.2/tech.tablesaw.api.Table.autoRegisterReadersAndWriters(Table.java:122)
	at tablesaw.core@0.38.2/tech.tablesaw.api.Table.<clinit>(Table.java:75)
	at jtablesaw/jtablesaw.Main.main(Main.java:23)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public void jdk.internal.misc.Unsafe.invokeCleaner(java.nio.ByteBuffer) accessible: module java.base does not "exports jdk.internal.misc" to unnamed module @41975e01
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:349)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:289)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:196)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:190)
	at nonapi.io.github.classgraph.utils.FileUtils.lookupCleanMethodPrivileged(FileUtils.java:587)
	at nonapi.io.github.classgraph.utils.FileUtils.access$000(FileUtils.java:55)
	at nonapi.io.github.classgraph.utils.FileUtils$2.run(FileUtils.java:607)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at nonapi.io.github.classgraph.utils.FileUtils.<clinit>(FileUtils.java:604)`

**Comment by lwhite1** [comment]
See #1051. 

It may be possible to address this specific part of the module issue by modifying the reader/writer register system.

**Comment by lwhite1** [comment]
Per Oracle, the workaround is: 

> 
> If you see IllegalAccessException or InaccessibleObjectException messages at runtime, you could use the --add-opens runtime option, basing the arguments upon the information shown in the exception message.
> 
> The syntax for --add-opens is:

`--add-opens module/package=target-module(,target-module)*`
